services:
  api-gateway:
    build:
      context: .

    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080

    env_file:
      - .env
    networks:
      - micro-network

networks:
  micro-network:
    external: true
