services:
  api-gateway:
    container_name: fastapi_gateway
    build:
      context: .
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - micro-network
    entrypoint: ""
    command: /api-gateway/scripts/healthcheck-entrypoint.sh
    restart: always

networks:
  micro-network:
    external: true
